version: '2.2'

volumes:
  bash-history:

services:
  dev:
    build: .
    image: app
    user: phantom
    init: true
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
